# Generated by Django 4.2.4 on 2023-08-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_candidate_id_alter_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
